# Generated by Django 3.0.3 on 2020-03-11 04:20

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200305_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.upload_product),
        ),
    ]
