# Generated by Django 3.0.3 on 2020-03-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20200305_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cards',
        ),
        migrations.AddField(
            model_name='cards',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.Users'),
        ),
    ]
