# Generated by Django 3.0.3 on 2020-03-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_auto_20200311_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='author',
        ),
    ]
