# Generated by Django 3.0.3 on 2020-03-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_cards_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='username',
        ),
    ]
