# Generated by Django 3.0.3 on 2020-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_auto_20200311_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destitute',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destitute',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
