# Generated by Django 3.0.3 on 2020-03-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_auto_20200312_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='description',
        ),
    ]
